apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dpod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dpod
    spec:
      containers:
      - name: dpod
        image: bogdando/dbox
        command: ["/bin/sleep", "10000000000"]
        imagePullPolicy: IfNotPresent
